//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_agesEntities2 : DbContext
    {
        public db_agesEntities2()
            : base("name=db_agesEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_anexo> tb_anexo { get; set; }
        public DbSet<tb_anexo_compra> tb_anexo_compra { get; set; }
        public DbSet<tb_anexo_empresa> tb_anexo_empresa { get; set; }
        public DbSet<tb_anexo_fatura> tb_anexo_fatura { get; set; }
        public DbSet<tb_anexo_orcamento> tb_anexo_orcamento { get; set; }
        public DbSet<tb_anexo_projeto> tb_anexo_projeto { get; set; }
        public DbSet<tb_campi> tb_campi { get; set; }
        public DbSet<tb_compra> tb_compra { get; set; }
        public DbSet<tb_contato> tb_contato { get; set; }
        public DbSet<tb_empresa> tb_empresa { get; set; }
        public DbSet<tb_endereco> tb_endereco { get; set; }
        public DbSet<tb_fatura> tb_fatura { get; set; }
        public DbSet<tb_forma_pagamento> tb_forma_pagamento { get; set; }
        public DbSet<tb_funcao> tb_funcao { get; set; }
        public DbSet<tb_mantenedora> tb_mantenedora { get; set; }
        public DbSet<tb_orcamento> tb_orcamento { get; set; }
        public DbSet<tb_orcamento_servico> tb_orcamento_servico { get; set; }
        public DbSet<tb_projeto> tb_projeto { get; set; }
        public DbSet<tb_projeto_servico> tb_projeto_servico { get; set; }
        public DbSet<tb_servico> tb_servico { get; set; }
        public DbSet<tb_status_orcamento> tb_status_orcamento { get; set; }
        public DbSet<tb_status_projeto> tb_status_projeto { get; set; }
        public DbSet<tb_usuario> tb_usuario { get; set; }
    }
}
