//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_anexo
    {
        public tb_anexo()
        {
            this.tb_compra = new HashSet<tb_compra>();

            this.tb_projeto = new HashSet<tb_projeto>();
            this.tb_fatura = new HashSet<tb_fatura>();

            this.tb_empresa = new HashSet<tb_empresa>();
            this.tb_orcamento = new HashSet<tb_orcamento>();
        }
        public int id { get; set; }
        public int id_usuario { get; set; }
        public string titulo { get; set; }
        public string anotacao { get; set; }
        public System.DateTime data_cadastro { get; set; }
        public int tamanho { get; set; }
        public string tipo { get; set; }
        public string caminho { get; set; }
        public string nome_arquivo { get; set; }
        public string url { get; set; }

        public virtual tb_usuario tb_usuario { get; set; }
        public virtual ICollection<tb_compra> tb_compra { get; set; }
        public virtual ICollection<tb_fatura> tb_fatura { get; set; }
        public virtual ICollection<tb_empresa> tb_empresa { get; set; }
        public virtual ICollection<tb_orcamento> tb_orcamento { get; set; }
        public virtual ICollection<tb_projeto> tb_projeto { get; set; }
    }
}
