//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_anexo
    {
        public int id { get; set; }
        public int id_usuario { get; set; }
        public string titulo { get; set; }
        public string anotacao { get; set; }
        public System.DateTime data_cadastro { get; set; }
        public int tamanho { get; set; }
        public string tipo { get; set; }
        public string caminho { get; set; }
        public string nome_arquivo { get; set; }
        public string url { get; set; }

        public virtual tb_usuario tb_usuario { get; set; }
        public virtual ICollection<tb_compra> tb_compra { get; set; }
    }
}
