//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_compra
    {
        public int id { get; set; }
        public int id_fatura { get; set; }
        public string anotacao { get; set; }
        public Nullable<System.DateTimeOffset> data_compra { get; set; }
        public decimal valor { get; set; }
    
        public virtual tb_fatura tb_fatura { get; set; }
    }
}
