//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_contato
    {
        public tb_contato()
        {
            this.tb_campi = new HashSet<tb_campi>();
            this.tb_empresa = new HashSet<tb_empresa>();
            this.tb_mantenedora = new HashSet<tb_mantenedora>();
        }
     
        public int id { get; set; }
        public string telefone { get; set; }
        public string fax { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string site { get; set; }

        public virtual ICollection<tb_campi> tb_campi { get; set; }
        public virtual ICollection<tb_empresa> tb_empresa { get; set; }
        public virtual ICollection<tb_mantenedora> tb_mantenedora { get; set; }

    }
}
