//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empresa
    {
        public int id { get; set; }
        public int id_endereco { get; set; }
        public int id_contato { get; set; }
        public string razao_social { get; set; }
        public string nome_fantasia { get; set; }
        public string cnpj { get; set; }
        public string inscricao_estadual { get; set; }
        public string inscricao_municipal { get; set; }
        public string atividade_principal { get; set; }
        public virtual tb_contato tb_contato { get; set; }
        public virtual ICollection<tb_orcamento> tb_orcamento { get; set; }
        public virtual tb_endereco tb_endereco { get; set; }
    }
}
