//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcao
    {
        public tb_funcao()
        {
            this.tb_usuario = new HashSet<tb_usuario>();
        }
        public int id { get; set; }
        public string nome { get; set; }
        public virtual ICollection<tb_usuario> tb_usuario { get; set; }
    }
}
