//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcao
    {
        public tb_funcao()
        {
            this.tb_usuario = new HashSet<tb_usuario>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public bool add_usuario { get; set; }
        public bool edt_usuario { get; set; }
        public bool add_empresa { get; set; }
        public bool edt_empresa { get; set; }
        public bool add_anexo_projeto { get; set; }
        public bool exl_anexo_projeto { get; set; }
        public bool add_projeto { get; set; }
        public bool exl_projeto { get; set; }
        public bool edt_projeto { get; set; }
        public bool add_orcamento_projeto { get; set; }
        public bool exl_orcamento_projeto { get; set; }
        public bool edt_orcamento_projeto { get; set; }
        public bool add_anexo_orcamento { get; set; }
        public bool exl_anexo_orcamento { get; set; }
        public bool add_fatura_orcamento { get; set; }
        public bool exl_fatura_orcamento { get; set; }
        public bool edt_fatura_orcamento { get; set; }
    
        public virtual ICollection<tb_usuario> tb_usuario { get; set; }
    }
}
