//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_orcamento_servico
    {
        public int id_orcamento { get; set; }
        public int id_servico { get; set; }
        public System.DateTime data_cadastro { get; set; }
        public string anotacao { get; set; }
        public decimal valor_servico { get; set; }
            
        public virtual tb_orcamento tb_orcamento { get; set; }
        public virtual tb_servico tb_servico { get; set; }
    }
}
