//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_orcamento
    {
        public int id { get; set; }
        public int id_usuario { get; set; }
        public int id_status { get; set; }
        public int id_empresa { get; set; }
        public int id_projeto { get; set; }
        public decimal valor { get; set; }
        public string anotacao { get; set; }

        public virtual tb_empresa tb_empresa { get; set; }
        public virtual ICollection<tb_fatura> tb_fatura { get; set; }
        public virtual ICollection<tb_orcamento_servico> tb_orcamento_servico { get; set; }
        public virtual tb_projeto tb_projeto { get; set; }
        public virtual tb_status_orcamento tb_status_orcamento { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
