//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_projeto_servico
    {
        public int id_projeto { get; set; }
        public int id_servico { get; set; }
        public System.DateTimeOffset data_cadastro { get; set; }
        public decimal valor_limite { get; set; }
        public string anotacao { get; set; }
    
        public virtual tb_projeto tb_projeto { get; set; }
        public virtual tb_servico tb_servico { get; set; }
    }
}
