//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_servico
    {
        public int id { get; set; }
        public int id_usuario { get; set; }
        public decimal valor { get; set; }
        public string titulo { get; set; }
        public string anotacao { get; set; }
        public System.DateTime data_cadastro { get; set; }
        public virtual ICollection<tb_orcamento_servico> tb_orcamento_servico { get; set; }
        public virtual ICollection<tb_projeto_servico> tb_projeto_servico { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
